[package]
name = "up-core-api-wit"
version = "0.1.0"
edition = "2024"

[dependencies]
wit-bindgen-rt = { version = "0.41.0", features = ["bitflags", "async"] }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "component:asyncdemo"

[package.metadata.component.dependencies]
