package uprotocol:basic;

interface uattributes {
    record uattributes {
        foo: u32
    }

  // Add a simple function that uses the uuid type
  // This ensures the type is included in bindings
  create-uattributes: func() -> uattributes;
}
