package uprotocol:basic;

interface utransport {
    use uuri.{uuri};
    use umessage.{umessage};

    register-listener: func(source-filter: uuri, sink-filter: uuri) -> future<string>;
    unregister-listener: func(source-filter: uuri, sink-filter: uuri) -> future<string>;
    send: func(message: umessage) -> future<string>;
    // receive: func(name: future<uuid>) -> future<string>;
}

